[package]
name = "motor_controller"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.128"
serde = { version = "1.0.210", features = [ "derive" ] }

[target.'cfg(target_os = "linux")'.dependencies]
rppal = "0.19.0" 
